# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/OliveTin/OliveTin
%global goipath         github.com/OliveTin/OliveTin
Version:                2022.11.14
%global tag             2022.11.14

%gometa -f

%global common_description %{expand:
OliveTin gives safe and simple access to predefined shell commands from a web
interface.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md README.md SECURITY.md

Name:           OliveTin
Release:        %autorelease
Summary:        Gives safe and simple access to predefined shell commands

Patch0: systemd-unit-path.patch

BuildRequires: systemd-rpm-macros
BuildRequires: googleapis-devel 
BuildRequires: protobuf-compiler
BuildRequires: protobuf-devel
BuildRequires: golang-google-grpc
BuildRequires: golang-google-protobuf
BuildRequires: golang-github-grpc-ecosystem-gateway-2

License:        AGPLv3
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

sed -i 's/local\///g' OliveTin.service

%build
make protoc

export LDFLAGS="-X main.version=%{version}%{dist} "
%gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/cmd/OliveTin

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -m 0644 -vD config.yaml         %{buildroot}/etc/OliveTin/config.yaml

install -m 0755 -vd                     %{buildroot}/usr/share/OliveTin/webui/

# rpmlint does not like hidden files
rm webui/.eslintrc.json
rm webui/.stylelintrc.json

cp -r webui %{buildroot}/usr/share/OliveTin/
find %{buildroot}/usr/share/OliveTin/webui -type f -exec chmod 0644 {} \;

install -m 0644 -vD var/manpage/OliveTin.1.gz %{buildroot}%{_mandir}/man1/OliveTin.1.gz

install -m 0644 -vD OliveTin.service %{buildroot}/%{_unitdir}/OliveTin.service

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CODE_OF_CONDUCT.md README.md SECURITY.md
%{_bindir}/*
%config(noreplace) /etc/OliveTin/config.yaml
/usr/share/OliveTin/*
/%{_mandir}/man1/OliveTin.1.gz
/%{_unitdir}/OliveTin.service

%gopkgfiles

%changelog
%autochangelog
